services:
  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_DB=tasks"
    volumes:
      - vol-postgres-db:/var/lib/postgresql/data
    profiles: ["db","dbfull","min-all","all"]
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9001:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=vikashsaini01@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    volumes:
      - vol-pgadmin:/var/lib/pgadmin
    profiles: ["dbfull","all"]
  tasks:
    build: ../Tasks/
    environment:
      - "spring.datasource.url=jdbc:postgresql://postgres-db:5432/tasks"
      - "spring.datasource.username=postgres"
      - "spring.datasource.password=mysecretpassword"
    ports:
      - "9051:8080"
    profiles: ["min-all","all"]
volumes:
    vol-postgres-db:
    vol-pgadmin:
    
    
# sudo docker-compose --profile min-all up --build